<?php

return [
    'seo' => [
        'title' => 'Md Mazharul Islam | Full Stack Developer',
        'description' => 'A dark, terminal-inspired developer portfolio for Md Mazharul Islam, focused on React, Node.js, TypeScript, and product-minded web engineering.',
    ],
    'profile' => [
        'brand' => 'dev Mazharul',
        'name' => 'Mazharul Islam',
        'title' => 'Full Stack Developer | React & Node.js',
        'intro' => 'I build fast, accessible web apps with clean interfaces, reliable APIs, and a product-minded engineering workflow.',
        'resumePath' => 'assets/resume.txt',
        'profileImage' => 'assets/mazharul-coder.png',
        'terminalRole' => 'full-stack-developer',
        'terminalStack' => 'react node typescript postgres docker',
        'typingMessages' => [
            'shipping thoughtful web experiences',
            'debugging edge cases before launch',
            'turning ideas into maintainable systems',
            'documenting the weird parts',
        ],
        'whatsappUrl' => 'https://wa.me/8801706452007',
        'footerQuote' => 'Ship small, learn fast.',
    ],
    'about' => [
        'eyebrow' => '01 / about',
        'heading' => 'Code With Product Sense',
        'paragraphs' => [
            'I enjoy turning messy requirements into focused software. My favorite work sits between frontend polish and backend reliability: dashboards, SaaS tools, automation flows, and platforms that make repeated tasks feel effortless.',
            'I care about readable code, resilient systems, strong defaults, and interfaces that stay calm even when the data is complex.',
        ],
        'stats' => [
            ['value' => '4+', 'label' => 'Years Building'],
            ['value' => '28', 'label' => 'Projects Shipped'],
            ['value' => '6', 'label' => 'Core Stacks'],
        ],
    ],
    'skills' => [
        'eyebrow' => '02 / skills',
        'heading' => 'Stack I Reach For',
        'groups' => [
            ['title' => 'Frontend', 'items' => ['React', 'Next.js', 'TypeScript', 'Tailwind', 'Accessibility']],
            ['title' => 'Backend', 'items' => ['Node.js', 'Express', 'REST', 'GraphQL', 'Auth']],
            ['title' => 'Database', 'items' => ['PostgreSQL', 'MongoDB', 'Prisma', 'Redis', 'Supabase']],
            ['title' => 'Tools', 'items' => ['Git', 'Docker', 'Vercel', 'CI/CD', 'Testing']],
        ],
    ],
    'projects' => [
        'eyebrow' => '03 / projects',
        'heading' => 'Featured Builds',
        'items' => [
            [
                'title' => 'Codex Seller',
                'role' => 'Founder',
                'image' => 'assets/01M0F8719QPD43VC7MH5ZVBEPN.jpg',
                'description' => 'A digital platform marketplace built for offering premium GPL WordPress themes, plugins, and web assets. Designed with a clean, modern user interface, intuitive search, and instant download capabilities to provide high-performance solutions for web developers and designers.',
                'stack' => ['PHP', 'JavaScript', 'Tailwind CSS', 'MySQL', 'Laravel'],
                'highlight' => 'Premium GPL themes & plugins platform with instant downloads and dynamic search.',
                'liveUrl' => 'https://codexsell.com/',
                'githubUrl' => null,
            ],
            [
                'title' => 'Nova Analytics',
                'image' => 'assets/project-nova-dashboard.png',
                'description' => 'Multi-tenant analytics dashboard with realtime metrics, role-based access, and export workflows.',
                'stack' => ['Next.js', 'Postgres', 'Prisma'],
                'highlight' => 'Reduced report load time by 42%.',
                'liveUrl' => '#',
                'githubUrl' => '#',
            ],
            [
                'title' => 'API Forge',
                'image' => 'assets/project-api-forge.png',
                'description' => 'Developer platform for designing, testing, and documenting REST endpoints from a shared schema.',
                'stack' => ['Node.js', 'OpenAPI', 'Redis'],
                'highlight' => 'Cut endpoint review cycles from days to hours.',
                'liveUrl' => '#',
                'githubUrl' => '#',
            ],
            [
                'title' => 'TaskFlow OS',
                'image' => 'assets/project-taskflow.png',
                'description' => 'Keyboard-first task manager with kanban views, focus timers, command palette, and offline sync.',
                'stack' => ['React', 'IndexedDB', 'Zustand'],
                'highlight' => 'Offline-first sync with conflict hints.',
                'liveUrl' => '#',
                'githubUrl' => '#',
            ],
            [
                'title' => 'DevShop',
                'image' => 'assets/project-devshop.png',
                'description' => 'Commerce starter kit with checkout, product search, inventory states, and admin tools.',
                'stack' => ['TypeScript', 'Stripe', 'MongoDB'],
                'highlight' => 'Improved checkout completion by 31%.',
                'liveUrl' => '#',
                'githubUrl' => '#',
            ],
            [
                'title' => 'Pulse CI',
                'image' => 'assets/project-pulse-ci.png',
                'description' => 'Build monitor for deployment pipelines with webhook ingestion, notifications, and release health checks.',
                'stack' => ['Docker', 'GitHub API', 'Webhooks'],
                'highlight' => 'Surfaced failing builds 60% faster.',
                'liveUrl' => '#',
                'githubUrl' => '#',
            ],
            [
                'title' => 'Signal Notes',
                'image' => 'assets/project-signal-notes.png',
                'description' => 'Markdown knowledge base with semantic search, backlink graph, and encrypted workspace exports.',
                'stack' => ['Next.js', 'Vector DB', 'MDX'],
                'highlight' => 'Searches 10k notes in under 200ms.',
                'liveUrl' => '#',
                'githubUrl' => '#',
            ],
        ],
    ],
    'experience' => [
        'eyebrow' => '04 / experience',
        'heading' => 'Work History',
        'items' => [
            [
                'period' => '2024 - Present',
                'location' => 'Remote',
                'role' => 'Full Stack Developer',
                'company' => 'PixelStack Labs',
                'bullets' => [
                    'Built customer dashboards with React, Next.js, and PostgreSQL.',
                    'Designed API contracts and reduced production support issues.',
                    'Added automated tests around billing and permission flows.',
                ],
                'technologies' => ['React', 'Next.js', 'PostgreSQL'],
            ],
            [
                'period' => '2022 - 2024',
                'location' => 'Dhaka',
                'role' => 'Frontend Engineer',
                'company' => 'OrbitSoft',
                'bullets' => [
                    'Shipped responsive SaaS interfaces with TypeScript and Tailwind.',
                    'Improved Core Web Vitals across high-traffic product pages.',
                    'Partnered with design to create reusable component patterns.',
                ],
                'technologies' => ['TypeScript', 'Tailwind', 'Performance'],
            ],
        ],
    ],
    'education' => [
        'eyebrow' => '05 / education',
        'heading' => 'Education',
        'items' => [
            [
                'period' => '2018 - 2022',
                'degree' => 'B.Sc. in Computer Science',
                'institute' => 'University Name',
                'details' => 'Relevant work: data structures, databases, web engineering.',
            ],
        ],
    ],
    'github' => [
        'eyebrow' => '06 / github',
        'heading' => 'Contribution Pulse',
        'repos' => [
            ['label' => 'github.com/yourname/nova-analytics', 'url' => '#'],
            ['label' => 'github.com/yourname/api-forge', 'url' => '#'],
        ],
        'graphLevels' => [0, 1, 2, 0, 3, 4, 1, 0, 2, 3, 1, 4, 0, 2, 1, 3, 4, 2, 0, 1, 3, 2, 4, 0, 1, 2, 3, 1, 0, 4, 2, 1, 3, 0, 2],
    ],
    'articles' => [
        'eyebrow' => '07 / articles',
        'heading' => 'Notes From The Build Log',
        'items' => [
            ['category' => 'Architecture', 'title' => 'Designing APIs That Stay Boring In Production', 'excerpt' => '', 'url' => '#'],
            ['category' => 'Frontend', 'title' => 'Making Dense Dashboards Feel Calm', 'excerpt' => '', 'url' => '#'],
            ['category' => 'Workflow', 'title' => 'My Release Checklist For Small Product Teams', 'excerpt' => '', 'url' => '#'],
        ],
    ],
    'contact' => [
        'eyebrow' => '08 / contact',
        'heading' => "Let's Build Something Together",
        'email' => 'hello@example.com',
        'links' => [
            ['label' => 'LinkedIn', 'url' => '#'],
            ['label' => 'GitHub', 'url' => '#'],
            ['label' => 'Twitter / X', 'url' => '#'],
            ['label' => 'Discord', 'url' => '#'],
        ],
    ],
];
